### ISSUE TITLE
Give a warning when a package contains `.rda` files

### ISSUE THREAD

**Issue by MahShaaban** [helske/changer#4]
Hi @helske 
Data saved in a package can cause problems when changing the package names. I am not sure if there is a way to deal with this in `changer`, other than reading the files after changing the name.
I ran into this problem recently and the error message was not very informative. It would be nice if `changer` produced an error when `.rda` files are detected. 
What do you think?

**Comment by helske** [comment]
Thanks, good point, I forgot to consider this originally. Warning and suggestion to load and resave the file would probably be sufficient here.

**Comment by helske** [comment]
Hi @MahShaaban I hadn't noticed earlier that you made a fix regarding this in your own fork, if you make a pull request to this main repo I can merge this (and the other one you have made).

**Comment by MahShaaban** [comment]
Done. Thanks.
